// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VadodaraByFoot.AppResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VadodaraByFoot.AppResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        internal static string PlacheholderPassword {
            get {
                return ResourceManager.GetString("PlacheholderPassword", resourceCulture);
            }
        }
        
        internal static string lblForgotPass {
            get {
                return ResourceManager.GetString("lblForgotPass", resourceCulture);
            }
        }
        
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        internal static string lblDnthaveaccount {
            get {
                return ResourceManager.GetString("lblDnthaveaccount", resourceCulture);
            }
        }
        
        internal static string lblRegistration {
            get {
                return ResourceManager.GetString("lblRegistration", resourceCulture);
            }
        }
        
        internal static string PlacheholderMobNo {
            get {
                return ResourceManager.GetString("PlacheholderMobNo", resourceCulture);
            }
        }
        
        internal static string PlacheholderName {
            get {
                return ResourceManager.GetString("PlacheholderName", resourceCulture);
            }
        }
        
        internal static string PlacheholderLastName {
            get {
                return ResourceManager.GetString("PlacheholderLastName", resourceCulture);
            }
        }
        
        internal static string PlacheholderFirstName {
            get {
                return ResourceManager.GetString("PlacheholderFirstName", resourceCulture);
            }
        }
        
        internal static string PlacheholderConfirmPass {
            get {
                return ResourceManager.GetString("PlacheholderConfirmPass", resourceCulture);
            }
        }
        
        internal static string lblAlreadyhaveaccount {
            get {
                return ResourceManager.GetString("lblAlreadyhaveaccount", resourceCulture);
            }
        }
        
        internal static string lblAgreeTermCondition {
            get {
                return ResourceManager.GetString("lblAgreeTermCondition", resourceCulture);
            }
        }
        
        internal static string lblAgreeTermConditionLink {
            get {
                return ResourceManager.GetString("lblAgreeTermConditionLink", resourceCulture);
            }
        }
        
        internal static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        internal static string Placheholder_UsernameEmail {
            get {
                return ResourceManager.GetString("Placheholder_UsernameEmail", resourceCulture);
            }
        }
        
        internal static string PlacheholderFullName {
            get {
                return ResourceManager.GetString("PlacheholderFullName", resourceCulture);
            }
        }
        
        internal static string PlaceHolderEmailAddress {
            get {
                return ResourceManager.GetString("PlaceHolderEmailAddress", resourceCulture);
            }
        }
        
        internal static string PlacheholderSubject {
            get {
                return ResourceManager.GetString("PlacheholderSubject", resourceCulture);
            }
        }
        
        internal static string PlacheholderMessage {
            get {
                return ResourceManager.GetString("PlacheholderMessage", resourceCulture);
            }
        }
        
        internal static string LbtnSubmit {
            get {
                return ResourceManager.GetString("LbtnSubmit", resourceCulture);
            }
        }
        
        internal static string LbtnCancel {
            get {
                return ResourceManager.GetString("LbtnCancel", resourceCulture);
            }
        }
        
        internal static string LForgotPassDetailText {
            get {
                return ResourceManager.GetString("LForgotPassDetailText", resourceCulture);
            }
        }
        
        internal static string LLogoutSucessful {
            get {
                return ResourceManager.GetString("LLogoutSucessful", resourceCulture);
            }
        }
        
        internal static string LLogoutUnSucessful {
            get {
                return ResourceManager.GetString("LLogoutUnSucessful", resourceCulture);
            }
        }
        
        internal static string LSomethingWentWrong {
            get {
                return ResourceManager.GetString("LSomethingWentWrong", resourceCulture);
            }
        }
        
        internal static string LWebserverNotResponding {
            get {
                return ResourceManager.GetString("LWebserverNotResponding", resourceCulture);
            }
        }
        
        internal static string LNoInternetConnection {
            get {
                return ResourceManager.GetString("LNoInternetConnection", resourceCulture);
            }
        }
        
        internal static string LNoRecordsFound {
            get {
                return ResourceManager.GetString("LNoRecordsFound", resourceCulture);
            }
        }
        
        internal static string LError {
            get {
                return ResourceManager.GetString("LError", resourceCulture);
            }
        }
        
        internal static string LExitApp {
            get {
                return ResourceManager.GetString("LExitApp", resourceCulture);
            }
        }
        
        internal static string LNo {
            get {
                return ResourceManager.GetString("LNo", resourceCulture);
            }
        }
        
        internal static string LOk {
            get {
                return ResourceManager.GetString("LOk", resourceCulture);
            }
        }
        
        internal static string LYes {
            get {
                return ResourceManager.GetString("LYes", resourceCulture);
            }
        }
        
        internal static string LExit {
            get {
                return ResourceManager.GetString("LExit", resourceCulture);
            }
        }
        
        internal static string LOf {
            get {
                return ResourceManager.GetString("LOf", resourceCulture);
            }
        }
        
        internal static string LMessage {
            get {
                return ResourceManager.GetString("LMessage", resourceCulture);
            }
        }
        
        internal static string LInValidEmail {
            get {
                return ResourceManager.GetString("LInValidEmail", resourceCulture);
            }
        }
        
        internal static string LCall {
            get {
                return ResourceManager.GetString("LCall", resourceCulture);
            }
        }
        
        internal static string LDialNumber {
            get {
                return ResourceManager.GetString("LDialNumber", resourceCulture);
            }
        }
        
        internal static string LOfcAdress {
            get {
                return ResourceManager.GetString("LOfcAdress", resourceCulture);
            }
        }
        
        internal static string LOfcName {
            get {
                return ResourceManager.GetString("LOfcName", resourceCulture);
            }
        }
        
        internal static string LOfcPhoneNum {
            get {
                return ResourceManager.GetString("LOfcPhoneNum", resourceCulture);
            }
        }
        
        internal static string LOfcEmail {
            get {
                return ResourceManager.GetString("LOfcEmail", resourceCulture);
            }
        }
        
        internal static string TRegister {
            get {
                return ResourceManager.GetString("TRegister", resourceCulture);
            }
        }
        
        internal static string TLogin {
            get {
                return ResourceManager.GetString("TLogin", resourceCulture);
            }
        }
        
        internal static string TForgotPass {
            get {
                return ResourceManager.GetString("TForgotPass", resourceCulture);
            }
        }
        
        internal static string TWalktourList {
            get {
                return ResourceManager.GetString("TWalktourList", resourceCulture);
            }
        }
        
        internal static string TFAQ {
            get {
                return ResourceManager.GetString("TFAQ", resourceCulture);
            }
        }
        
        internal static string TAboutUs {
            get {
                return ResourceManager.GetString("TAboutUs", resourceCulture);
            }
        }
        
        internal static string TContactUs {
            get {
                return ResourceManager.GetString("TContactUs", resourceCulture);
            }
        }
        
        internal static string TFeedback {
            get {
                return ResourceManager.GetString("TFeedback", resourceCulture);
            }
        }
        
        internal static string TWalkTouDetail {
            get {
                return ResourceManager.GetString("TWalkTouDetail", resourceCulture);
            }
        }
        
        internal static string TRouteCoversDetail {
            get {
                return ResourceManager.GetString("TRouteCoversDetail", resourceCulture);
            }
        }
        
        internal static string LEmptyEmail {
            get {
                return ResourceManager.GetString("LEmptyEmail", resourceCulture);
            }
        }
        
        internal static string LEmptyEmailUsername {
            get {
                return ResourceManager.GetString("LEmptyEmailUsername", resourceCulture);
            }
        }
        
        internal static string LEmptyPassword {
            get {
                return ResourceManager.GetString("LEmptyPassword", resourceCulture);
            }
        }
        
        internal static string LPassNotMatch {
            get {
                return ResourceManager.GetString("LPassNotMatch", resourceCulture);
            }
        }
        
        internal static string LEmptyUserName {
            get {
                return ResourceManager.GetString("LEmptyUserName", resourceCulture);
            }
        }
        
        internal static string LEmptyFirstName {
            get {
                return ResourceManager.GetString("LEmptyFirstName", resourceCulture);
            }
        }
        
        internal static string LEmptyLastName {
            get {
                return ResourceManager.GetString("LEmptyLastName", resourceCulture);
            }
        }
        
        internal static string LEmptyMobileNo {
            get {
                return ResourceManager.GetString("LEmptyMobileNo", resourceCulture);
            }
        }
        
        internal static string LEmptyFullName {
            get {
                return ResourceManager.GetString("LEmptyFullName", resourceCulture);
            }
        }
        
        internal static string LEmptySubject {
            get {
                return ResourceManager.GetString("LEmptySubject", resourceCulture);
            }
        }
        
        internal static string LEmptyMessage {
            get {
                return ResourceManager.GetString("LEmptyMessage", resourceCulture);
            }
        }
        
        internal static string LDownloadPodcast {
            get {
                return ResourceManager.GetString("LDownloadPodcast", resourceCulture);
            }
        }
        
        internal static string LDownloading {
            get {
                return ResourceManager.GetString("LDownloading", resourceCulture);
            }
        }
        
        internal static string LAbt_Vadodara_By_Foot {
            get {
                return ResourceManager.GetString("LAbt_Vadodara_By_Foot", resourceCulture);
            }
        }
        
        internal static string MHome {
            get {
                return ResourceManager.GetString("MHome", resourceCulture);
            }
        }
        
        internal static string MAboutUs {
            get {
                return ResourceManager.GetString("MAboutUs", resourceCulture);
            }
        }
        
        internal static string MContactUs {
            get {
                return ResourceManager.GetString("MContactUs", resourceCulture);
            }
        }
        
        internal static string MFeedback {
            get {
                return ResourceManager.GetString("MFeedback", resourceCulture);
            }
        }
        
        internal static string MShare {
            get {
                return ResourceManager.GetString("MShare", resourceCulture);
            }
        }
        
        internal static string MFAQs {
            get {
                return ResourceManager.GetString("MFAQs", resourceCulture);
            }
        }
        
        internal static string MSettings {
            get {
                return ResourceManager.GetString("MSettings", resourceCulture);
            }
        }
        
        internal static string MLogout {
            get {
                return ResourceManager.GetString("MLogout", resourceCulture);
            }
        }
        
        internal static string MLogin {
            get {
                return ResourceManager.GetString("MLogin", resourceCulture);
            }
        }
        
        internal static string LLengthPassword {
            get {
                return ResourceManager.GetString("LLengthPassword", resourceCulture);
            }
        }
        
        internal static string LLengthUserNname {
            get {
                return ResourceManager.GetString("LLengthUserNname", resourceCulture);
            }
        }
        
        internal static string LLengthEmail {
            get {
                return ResourceManager.GetString("LLengthEmail", resourceCulture);
            }
        }
        
        internal static string LLengthMobNum {
            get {
                return ResourceManager.GetString("LLengthMobNum", resourceCulture);
            }
        }
        
        internal static string LLengthSubject {
            get {
                return ResourceManager.GetString("LLengthSubject", resourceCulture);
            }
        }
        
        internal static string LLengthMessage {
            get {
                return ResourceManager.GetString("LLengthMessage", resourceCulture);
            }
        }
        
        internal static string LtxtbxSearchTour {
            get {
                return ResourceManager.GetString("LtxtbxSearchTour", resourceCulture);
            }
        }
    }
}
